Repository s222792/Digital-Blackboard, pull requests merged in 2023-12, with the labels that each got.

#33 Added search bar to every page and redesigned it. Updated date_created for event creation dialogs
  digital-blackboard/src/components/dualLiving/DualLivingPage.vue
  digital-blackboard/src/components/eventsParties/EventsPartiesPage.vue
  digital-blackboard/src/components/studyHub/StudyHubPage.vue
Labels: enhancement, Dual Living, Study Hub, Events & Feiern

#44 Changed button designs
  digital-blackboard/src/components/dualLiving/DualLivingCard.vue
  digital-blackboard/src/components/dualLiving/DualLivingPage.vue
  digital-blackboard/src/components/eventsParties/EventsPartiesPage.vue
  digital-blackboard/src/components/studyHub/StudyHubPage.vue
  digital-blackboard/src/components/util/CustomCard.vue
Labels: Dual Living, Study Hub, Events & Feiern

#45 Changed dual living entries into offerings - right branch
  digital-blackboard/src/components/dualLiving/DualLivingPage.vue
Labels: Dual Living

#46 added correct DHBW color code
  digital-blackboard/src/components/blackBoard/BlackBoard.vue
  digital-blackboard/src/components/dualLiving/DualLivingPage.vue
  digital-blackboard/src/components/eventsParties/EventsPartiesPage.vue
  digital-blackboard/src/components/studyHub/StudyHubPage.vue
  digital-blackboard/src/components/util/CustomAppBar.vue
Labels: Dual Living, Study Hub, Events & Feiern, Blackboard

#49 Replaced category buttons by tabs, added new advertisements
  digital-blackboard/src/components/eventsParties/EventsPartiesPage.vue
Labels: enhancement, Events & Feiern

#56 Implemented Google Firebase cloud database
  digital-blackboard/package-lock.json
  digital-blackboard/package.json
  digital-blackboard/src/components/dualLiving/AddAppartmentDialog.vue
  digital-blackboard/src/components/dualLiving/DualLivingPage.vue
  digital-blackboard/src/components/eventsParties/AddEventDialog.vue
  digital-blackboard/src/components/studyHub/AddStudyBuddyDialog.vue
  digital-blackboard/src/components/studyHub/StudyHubBuddyCard.vue
  digital-blackboard/src/db.js
Labels: enhancement

#62 Restored main to a stable version and implemented firebase database
  digital-blackboard/package-lock.json
  digital-blackboard/package.json
  digital-blackboard/src/components/dualLiving/AddAppartmentDialog.vue
  digital-blackboard/src/components/dualLiving/DualLivingPage.vue
  digital-blackboard/src/components/eventsParties/AddEventDialog.vue
  digital-blackboard/src/components/eventsParties/AddSeminarDialog.vue
  digital-blackboard/src/components/eventsParties/EventsPartiesCard.vue
  digital-blackboard/src/components/eventsParties/EventsPartiesPage.vue
  digital-blackboard/src/components/studyHub/AddStudyBuddyDialog.vue
  digital-blackboard/src/components/studyHub/StudyHubBuddyCard.vue
  digital-blackboard/src/components/studyHub/StudyHubPage.vue
  digital-blackboard/src/db.js
Labels: bug

#65 added correct DHBW color code
  digital-blackboard/src/components/eventsParties/EventsPartiesPage.vue
  digital-blackboard/src/components/util/CustomAppBar.vue
Labels: Blackboard

#69 Fixed Webapp not executable anymore
  digital-blackboard/src/components/eventsParties/EventsPartiesPage.vue
Labels: bug, Events & Feiern

#72 Fixed displaying correct property in contact info dialog
  digital-blackboard/src/components/studyHub/StudyHubBuddyCard.vue
Labels: bug, Study Hub

#77 Implemented ability to share an advertisement
  digital-blackboard/src/components/dualLiving/DualLivingPage.vue
  digital-blackboard/src/components/eventsParties/EventsPartiesCard.vue
  digital-blackboard/src/components/eventsParties/EventsPartiesPage.vue
  digital-blackboard/src/components/studyHub/StudyHubPage.vue
  digital-blackboard/src/components/util/CustomCard.vue
Labels: bug, Dual Living, Study Hub, Events & Feiern

#81 Fixed duplicate methods
  digital-blackboard/src/components/eventsParties/EventsPartiesCard.vue
Labels: bug

#100 Added ability to like events and workshops
  digital-blackboard/src/components/eventsParties/EventsPartiesCard.vue
  digital-blackboard/src/db.js
Labels: enhancement, Events & Feiern

#102 Fixed bug that joining groups isn't working
  digital-blackboard/src/components/studyHub/StudyHubGroupCard.vue
  digital-blackboard/src/db.js
  digital-blackboard/src/views/StudyHubView.vue
Labels: bug, Study Hub

#108 Reload events after deletion, fixed study hub contents
  digital-blackboard/src/components/eventsParties/EventsPartiesCard.vue
  digital-blackboard/src/db.js
Labels: bug, Study Hub, Account Page

#109 Implementierung der Share Funktion
  digital-blackboard/src/components/eventsParties/EventsPartiesCard.vue
  digital-blackboard/src/components/studyHub/StudyHubBuddyCard.vue
  digital-blackboard/src/components/studyHub/StudyHubGroupCard.vue
  digital-blackboard/src/components/util/CustomCard.vue
  digital-blackboard/src/views/AccountView.vue
  digital-blackboard/src/views/DualLivingView.vue
  digital-blackboard/src/views/EventsPartiesView.vue
  digital-blackboard/src/views/StudyHubView.vue
Labels: enhancement

#118 Dev yannick bestätigungsdialog
  digital-blackboard/src/components/dualLiving/DualLivingCard.vue
  digital-blackboard/src/components/eventsParties/EventsPartiesCard.vue
  digital-blackboard/src/components/studyHub/AddStudyHubDialog.vue
  digital-blackboard/src/components/studyHub/EditStudyHubGroup.vue
  digital-blackboard/src/components/studyHub/StudyHubBuddyCard.vue
  digital-blackboard/src/components/studyHub/StudyHubGroupCard.vue
  digital-blackboard/src/components/util/ConfirmDialog.vue
  digital-blackboard/src/components/util/CustomCard.vue
  digital-blackboard/src/views/DualLivingView.vue
Labels: enhancement

#119 Show images in edit dialogs, fixed community not displayed
  digital-blackboard/src/components/dualLiving/DualLivingCard.vue
  digital-blackboard/src/components/dualLiving/EditAppartmentDialog.vue
  digital-blackboard/src/components/eventsParties/EditEventDialog.vue
  digital-blackboard/src/components/eventsParties/EditInfoDialog.vue
  digital-blackboard/src/components/eventsParties/EditSeminarDialog.vue
  digital-blackboard/src/components/eventsParties/EventsPartiesCard.vue
  digital-blackboard/src/components/studyHub/EditStudyBuddyDialog.vue
  digital-blackboard/src/components/studyHub/EditStudyHubGroup.vue
  digital-blackboard/src/components/util/UploadImagesStep.vue
Labels: bug, enhancement

#121 Fixed corrupted main branch
  digital-blackboard/src/components/dualLiving/DualLivingCard.vue
  digital-blackboard/src/components/eventsParties/EventsPartiesCard.vue
  digital-blackboard/src/components/util/UploadImagesStep.vue
Labels: bug

#131 Implemented ability to edit advertisements
  digital-blackboard/src/components/dualLiving/DualLivingCard.vue
  digital-blackboard/src/components/eventsParties/EditEventDialog.vue
  digital-blackboard/src/components/eventsParties/EventsPartiesCard.vue
  digital-blackboard/src/components/studyHub/EditStudyBuddyDialog.vue
  digital-blackboard/src/components/studyHub/StudyHubBuddyCard.vue
  digital-blackboard/src/components/studyHub/StudyHubGroupCard.vue
  digital-blackboard/src/db.js
  digital-blackboard/src/views/AccountView.vue
  digital-blackboard/src/views/DualLivingView.vue
  digital-blackboard/src/views/EventsPartiesView.vue
Labels: enhancement

#134 Removed corrupting comments in styles
  digital-blackboard/src/components/dualLiving/AddAppartmentDialog.vue
  digital-blackboard/src/components/eventsParties/AddEventDialog.vue
  digital-blackboard/src/components/eventsParties/AddInfoDialog.vue
  digital-blackboard/src/components/eventsParties/AddSeminarDialog.vue
  digital-blackboard/src/components/studyHub/AddStudyBuddyDialog.vue
  digital-blackboard/src/components/studyHub/AddStudyHubDialog.vue
Labels: bug

#142 Fixed maximum amount of participants not shown in edit dialog
  digital-blackboard/src/components/eventsParties/EditEventDialog.vue
  digital-blackboard/src/components/eventsParties/EditSeminarDialog.vue
  digital-blackboard/src/db.js
Labels: bug

#145 fix more information text in cards centered
  digital-blackboard/src/components/util/CustomCard.vue
  digital-blackboard/src/components/util/UploadImagesStep.vue
Labels: bug

#150 Fixed contact card now showing up
  digital-blackboard/src/components/studyHub/StudyHubBuddyCard.vue
Labels: bug

#173 Fixed default images, cleaned code
  digital-blackboard/src/App.vue
  digital-blackboard/src/components/dualLiving/AddAppartmentDialog.vue
  digital-blackboard/src/components/dualLiving/DualLivingCard.vue
  digital-blackboard/src/components/dualLiving/EditAppartmentDialog.vue
  digital-blackboard/src/components/eventsParties/AddEventDialog.vue
  digital-blackboard/src/components/eventsParties/AddInfoDialog.vue
  digital-blackboard/src/components/eventsParties/AddSeminarDialog.vue
  digital-blackboard/src/components/eventsParties/EditEventDialog.vue
  digital-blackboard/src/components/eventsParties/EditInfoDialog.vue
  digital-blackboard/src/components/eventsParties/EditSeminarDialog.vue
  digital-blackboard/src/components/eventsParties/EventsPartiesCard.vue
  digital-blackboard/src/components/studyHub/AddStudyBuddyDialog.vue
  digital-blackboard/src/components/studyHub/AddStudyHubDialog.vue
  digital-blackboard/src/components/studyHub/EditStudyBuddyDialog.vue
  digital-blackboard/src/components/studyHub/EditStudyHubGroup.vue
  digital-blackboard/src/components/studyHub/StudyHubBuddyCard.vue
  digital-blackboard/src/components/studyHub/StudyHubGroupCard.vue
  digital-blackboard/src/components/util/ConfirmDialog.vue
  digital-blackboard/src/components/util/ContactCard.vue
  digital-blackboard/src/components/util/CustomAppBar.vue
  digital-blackboard/src/components/util/CustomCard.vue
  digital-blackboard/src/components/util/CustomNavBar.vue
  digital-blackboard/src/db.js
  digital-blackboard/src/main.js
  digital-blackboard/src/router/index.js
  digital-blackboard/src/views/AccountView.vue
  digital-blackboard/src/views/BlackBoardView.vue
  digital-blackboard/src/views/DualLivingView.vue
  digital-blackboard/src/views/EventsPartiesView.vue
  digital-blackboard/src/views/StudyHubView.vue
Labels: bug
